name: Integration Tests
on:
  workflow_call:
    inputs:
      upload-pages-artifact:
        type: boolean
        required: false
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Setup Node.js environment
        uses: actions/setup-node@v2 
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run integration tests
        run: npm run test:integration
